---
- hosts: all
  sudo: yes
  roles:
    - common

- hosts: usenet
  sudo: yes
  roles:
    - usenet-auto-automation

- hosts: usenet
  sudo: yes
  roles:
    - nzbget

- hosts: usenet
  sudo: yes
  roles:
    - couchpotato

- hosts: usenet
  sudo: yes
  roles:
    - headphones