---
- hosts: all
  sudo: yes
  roles:
    - common

- hosts: usenet
  sudo: yes
  roles:
    - nzbget
  tags:
    - nzbget

- hosts: usenet
  sudo: yes
  roles:
    - sonarr
  tags:
    - sonarr

- hosts: usenet
  sudo: yes
  roles:
    - couchpotato
  tags:
    - couchpotato

- hosts: usenet
  sudo: yes
  roles:
    - headphones
  tags:
    - headphones