---

- name: Create headphones User
  user: name=headphones shell=/bin/bash groups=usenet append=yes

- name: Install git
  yum: name=git state=latest

- name: Git Clone headphones source from GitHub
  git: repo=https://github.com/rembo10/headphones.git
       dest=/opt/headphones

- name: Add empty config file
  file: dest=/opt/headphones/headphones.ini state=touch

- name: Set permissions on headphones directory
  file: path=/opt/headphones state=directory owner=headphones group=usenet recurse=yes

- name: Copy over headphones systemd unit file
  copy: src=headphones.service dest=/etc/systemd/system/
  notify:
    - reload systemd
    - restart headphones

- name: Enable headphones service
  service: name=headphones enabled=yes

- name: Add headphones firewalld entry
  firewalld: port=8181/tcp permanent=true state=enabled immediate=yes

##Broken after upgrading to Ansible 2.0. 
#TODO: Modify correct file for default config
#- name: Change headphones to listen on 0.0.0.0 instead of localhost
#  lineinfile: dest=/opt/headphones/headphones/config.py
#              regexp=^"    'HTTP_HOST'"
#              line="    'HTTP_HOST'":" (str, 'General', '0.0.0.0'),"

#TODO: Remove this hack to get correct config.
- name: Remove default config so new one is created
  file: path=/opt/headphones/headphones.ini state=absent