---
- name: Install git
  yum: name=git state=latest

- name: Git Clone CouchPotato source from GitHub
  - git: repo=https://github.com/RuudBurger/CouchPotatoServer.git
       dest=/opt/couchpotato

- nme: Create CouchPotato User
  user: name=couchpotato shell=/bin/bash groups=usenet append=yes

- name: Change permissions on CouchPotato directory
  file: path=/opt/couchpotato state=directory mode=0755 owner=couchpotato
