---
- nme: Create NZBget User
  user: name=nzbget shell=/bin/bash groups=usenet append=yes

- name: Create folder for NZBget
  file: path=/opt/nzbget state=directory mode=0755

- name: Fetch NZBget Installer
  get_url: url=https://github.com/nzbget/nzbget/releases/download/v15.0/nzbget-15.0-bin-linux.run dest=/opt/nzbget mode=0755

  name: Copy over NZBget systemd unit file
  file: src=nzbget.service dest=/etc/systemd/system/
  notify:
    - reload systemd
    - restart nzbget

- name: Enable NZBget firewalld rules
  firewalld: service=nzbget permanent=true state=enabled
    notify:
    - reload firewalld

#TODO: Put this where it belongs
- name: Start and Enable NZBget
  service: name=nzbget enabled=yes state=started

#TODO: Put this where it belongs
- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
