---

- name: Create Sonarr User
  user: name=sonarr shell=/bin/bash groups=usenet append=yes

- name: Put OpenSuse CentOS7 Mono Repo in place
  get_url: url=http://download.opensuse.org/repositories/home:/tpokorra:/mono/CentOS_CentOS-7/home:tpokorra:mono.repo dest=/etc/yum.repos.d/mono.repo

- name: Install prerequisites for Sonarr
  yum: name={{ item }}
  with_items:
    - mediainfo 
    - libzen 
    - libmediainfo
    - curl 
    - gettext 
    - mono-opt
    - sqlite.x86_64 

#- name: Install Mono
#  yum: name={{ with_items }}
#  with_items:
#    - mono-opt-3.4 
#    - mono-opt-3.4-devel

- name: Create Mono symlink
  file: src=/opt/mono/bin/mono dest=/usr/bin/mono state=link

- name: Wget NzbDrone.master.tar.gz
  get_url: url=http://update.sonarr.tv/v2/master/mono/NzbDrone.master.tar.gz dest=/tmp/

- name: Extract Sonarr
  unarchive: src=/tmp/NzbDrone.master.tar.gz dest=/opt/ owner=sonarr group=usenet copy=no

- name: Copy over Sonarr systemd unit file
  copy: src=sonarr.service dest=/etc/systemd/system/sonarr.service
#  notify:
#    - reload systemd
#    - restart sonarr

- name: reload systemd
  command: systemctl daemon-reload

- name: Copy Sonarr firewalld file in place
  copy: src=sonarr.xml dest=/etc/firewalld/services/

- name: reload firewalld
  command: firewall-cmd --reload

- name: Enable Sonarr firewalld rules
  firewalld: service=sonarr permanent=true state=enabled immediate=yes
#  notify:
#    - reload firewalld

#TODO: Put this where it belongs
- name: Start and Enable Sonarr
  service: name=sonarr enabled=yes

#TODO: Remove when notifies work properly
- name: restart Sonarr
  service: name=sonarr state=restarted
