---

- name: Create Sonarr User
  user: name=sonarr shell=/bin/bash groups=usenet append=yes

- name: Add ubuntu keyserver.ubuntu.com for mono
  rpm_key: state=present key=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Add Mono repo
  yumrepo:
    name: mono-project
    description: mono YUM repo
    baseurl: http://download.mono-project.com/repo/centos/

- name: Install prerequisites for Sonarr
  yum: name={{ item }}
  with_items:
    - mediainfo 
    - libzen 
    - libmediainfo
    - curl 
    - gettext 
    - mono-complete
    - sqlite.x86_64

- name: Wget NzbDrone.master.tar.gz
  get_url: url=http://update.sonarr.tv/v2/master/mono/NzbDrone.master.tar.gz dest=/tmp/

- name: Extract Sonarr
  unarchive: src=/tmp/NzbDrone.master.tar.gz dest=/opt/ owner=sonarr group=usenet copy=no

- name: Copy over Sonarr systemd unit file
  copy: src=sonarr.service dest=/etc/systemd/system/sonarr.service
#  notify:
#    - reload systemd
#    - restart sonarr

- name: reload systemd
  command: systemctl daemon-reload

- name: Copy Sonarr firewalld file in place
  copy: src=sonarr.xml dest=/etc/firewalld/services/

- name: reload firewalld
  command: firewall-cmd --reload

- name: Enable Sonarr firewalld rules
  firewalld: service=sonarr permanent=true state=enabled immediate=yes
#  notify:
#    - reload firewalld

#TODO: Put this where it belongs
- name: Start and Enable Sonarr
  service: name=sonarr enabled=yes

#TODO: Remove when notifies work properly
- name: restart Sonarr
  service: name=sonarr state=restarted
