---
- name: Install Packages
  yum: name={{ item }}
  with_items:
    - p7zip
    - par2cmdline

- name: Create NZBget User
  user: name=nzbget shell=/bin/bash groups=usenet append=yes

- name: Fetch NZBget Installer
  get_url: url=https://github.com/nzbget/nzbget/releases/download/v15.0/nzbget-15.0-bin-linux.run dest=/opt/ mode=0755

- name: Run Installer
  command: /opt/nzbget-15.0-bin-linux.run --destdir /opt/nzbget

- name: Set NZBget directory Owner
  file: path=/opt/nzbget owner=nzbget group=usenet state=directory recurse=yes

- name: Clean Up Installer
  file: path=/opt/nzbget-15.0-bin-linux.run state=absent

- name: Copy over NZBget systemd unit file
  copy: src=nzbget.service dest=/etc/systemd/system/nzbget.service
  notify:
    - reload systemd
    - restart nzbget

- name: Enable NZBget service
  service: name=nzbget enabled=yes

- name: Add NZBget firewalld entry
  firewalld: port=6789/tcp permanent=true state=enabled immediate=yes
