---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart systemd
  service: name=systemd state=restarted

- name: reload firewalld
  command: firewall-cmd --reload

- name: restart firewalld
  service: name=firewalld state=restarted

- name: restart couchpotato
  service: name=couchpotato state=restarted